const DATABASE_NAME = '@gameplay'

const COLLECTION_USERS = `${DATABASE_NAME}:user`;
const COLLECTION_APPOINTMENT = `${DATABASE_NAME}:appointment`;
const COLLECTION_APPOINTMENT_SELECTED = `${DATABASE_NAME}:appointment_selected`;

export {
    COLLECTION_USERS,
    COLLECTION_APPOINTMENT,
    COLLECTION_APPOINTMENT_SELECTED
}